// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
[Parallelizable]
public class CpAdminLoginTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    public string waitForWindow(int timeout)
    {
        try
        {
            Thread.Sleep(timeout);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
        var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
        if (whNow.Count > whThen.Count)
        {
            return whNow.Except(whThen).First().ToString();
        }
        else
        {
            return whNow.First().ToString();
        }
    }

    public void incorrectPassword()
    {
        driver.Navigate().GoToUrl("https://cp.staging.curogram.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1305, 700);
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        vars["WindowHandles"] = driver.WindowHandles;
        driver.FindElement(By.XPath("//div[contains(.,\'Sign In\')]")).Click();
        vars["win188"] = waitForWindow(2000);
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        vars["root"] = driver.CurrentWindowHandle;
        driver.SwitchTo().Window(vars["win188"].ToString());
        driver.FindElement(By.XPath("//input[@id=\'login-email\']")).Click();
        driver.FindElement(By.XPath("//input[@id=\'login-email\']")).SendKeys("testrigorcpuser@curogram.com");
        driver.FindElement(By.XPath("//input[@id=\'login-password\']")).Click();
        driver.FindElement(By.XPath("//input[@id=\'login-password\']")).SendKeys("incorrectpassword");
        try
        {
            Thread.Sleep(5000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        driver.FindElement(By.XPath("//span[contains(.,\'Log in\')]")).Click();
        try
        {
            Thread.Sleep(5000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        Assert.That(driver.FindElement(By.XPath("//div[@class=\'alert-red\']")).Text, Is.EqualTo("Your password is not matching our records."));
        driver.Close();
        driver.SwitchTo().Window(vars["root"].ToString());
        driver.Close();
    }

    public void loginSuccess()
    {
        driver.Navigate().GoToUrl("https://cp.staging.curogram.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1305, 700);
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        vars["WindowHandles"] = driver.WindowHandles;
        driver.FindElement(By.XPath("//div[contains(.,\'Sign In\')]")).Click();
        vars["win188"] = waitForWindow(2000);
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        vars["root"] = driver.CurrentWindowHandle;
        driver.SwitchTo().Window(vars["win188"].ToString());
        driver.FindElement(By.XPath("//input[@id=\'login-email\']")).Click();
        driver.FindElement(By.XPath("//input[@id=\'login-email\']")).SendKeys("testrigorcpuser@curogram.com");
        driver.FindElement(By.XPath("//input[@id=\'login-password\']")).Click();
        driver.FindElement(By.XPath("//input[@id=\'login-password\']")).SendKeys("password1");
        driver.FindElement(By.XPath("//span[contains(.,\'Log in\')]")).Click();
        driver.SwitchTo().Window(vars["root"].ToString());
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        Assert.That(driver.FindElement(By.XPath("//a[contains(text(),\'Admin panel\')]")).Text, Is.EqualTo("Admin panel"));
        driver.Close();
    }
    public void incorrectEmailFormat()
    {
        driver.Navigate().GoToUrl("https://cp.staging.curogram.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1305, 700);
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        vars["WindowHandles"] = driver.WindowHandles;
        driver.FindElement(By.XPath("//div[contains(.,\'Sign In\')]")).Click();
        vars["win188"] = waitForWindow(2000);
        try
        {
            Thread.Sleep(10000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        vars["root"] = driver.CurrentWindowHandle;
        driver.SwitchTo().Window(vars["win188"].ToString());
        driver.FindElement(By.XPath("//input[@id=\'login-email\']")).Click();
        driver.FindElement(By.XPath("//input[@id=\'login-email\']")).SendKeys("incorrectemailformat");
        driver.FindElement(By.XPath("//input[@id=\'login-password\']")).Click();
        try
        {
            Thread.Sleep(3000);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        var elements = driver.FindElements(By.XPath("//div[@class=\'bubble-error alert-red\']"));
        Assert.True(elements.Count > 0);
        driver.Close();
        driver.SwitchTo().Window(vars["root"].ToString());
        driver.Close();
    }
    [Test]
    public void CpAdminLogin()
    {
        CpAdminLoginTest a = new CpAdminLoginTest();
        a.incorrectEmailFormat();
        a.incorrectPassword();
        a.loginSuccess();
    }
}